// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRvraX4ntHLHUAwkz1bxcfbIZYyWDjrY',
    appId: '1:457077677543:web:db5633dd13363f6ea17142',
    messagingSenderId: '457077677543',
    projectId: 'kendjino-exchange',
    authDomain: 'kendjino-exchange.firebaseapp.com',
    storageBucket: 'kendjino-exchange.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQPHRnD9QGLs2sB1V8vxuu0qnydI5KiI',
    appId: '1:457077677543:android:4a1e52abeeeaa878a17142',
    messagingSenderId: '457077677543',
    projectId: 'kendjino-exchange',
    storageBucket: 'kendjino-exchange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3uEj87jXeTmpO7wyukxY5PK2wc4rEqY',
    appId: '1:457077677543:ios:aa8014cf5b4ef033a17142',
    messagingSenderId: '457077677543',
    projectId: 'kendjino-exchange',
    storageBucket: 'kendjino-exchange.firebasestorage.app',
    iosBundleId: 'com.example.kendjinoExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE3uEj87jXeTmpO7wyukxY5PK2wc4rEqY',
    appId: '1:457077677543:ios:aa8014cf5b4ef033a17142',
    messagingSenderId: '457077677543',
    projectId: 'kendjino-exchange',
    storageBucket: 'kendjino-exchange.firebasestorage.app',
    iosBundleId: 'com.example.kendjinoExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoRvraX4ntHLHUAwkz1bxcfbIZYyWDjrY',
    appId: '1:457077677543:web:797721a1f96341b6a17142',
    messagingSenderId: '457077677543',
    projectId: 'kendjino-exchange',
    authDomain: 'kendjino-exchange.firebaseapp.com',
    storageBucket: 'kendjino-exchange.firebasestorage.app',
  );
}
